apiVersion: v1
kind: Service
metadata:
  name: portfolio-app-lb
  namespace: portfolio-devops
spec:
  type: LoadBalancer
  selector:
    app: portfolio-app
  ports:
    - port: 80
      targetPort: 5000
